classDiagram
    direction TB

    class com_github_forax_umldoc_core_AssociationDependency {
      -entities: HashSet&lt;Entity&gt;
			+ONLY_ONE: AssociationDependency$Cardinality
			-entity: Entity
			-navigability: boolean
			-cardinality: AssociationDependency$Cardinality
			-fields: HashSet&lt;Field&gt;
			-name: String
			-_VALUES: AssociationDependency$Cardinality[]
			-label: Optional&lt;String&gt;
			+MANY: AssociationDependency$Cardinality
			 val_entityBuilder: ClassFileParser$EntityBuilder
			+ZERO_OR_ONE: AssociationDependency$Cardinality
    }